### ISSUE TITLE
Feature: Support for folders (to prevent the 'Folder In Use' error)

### ISSUE THREAD

**Issue by shcmack** [marianpekar/file-unlocker-for-windows#1]
When trying to rename a folder that contains file(s) that are currently open, you get the error: "_This action can't be completed because the folder or a file in it is open in another program_". That happens all the time, and USB devices that won't undock because a process is still paired with it. This utility would be perfect if it could handle these cases too, because the way it is integrated and works is great! :)

**Comment by ko6an** [comment]
Very important feature 🙄

**Comment by Maxhem2** [comment]
I second this, it's what all the other tools are missing

**Comment by marianpekar** [comment]
Hi, do I understand correctly that what you'd expect from such a feature would be that when renaming a folder that contains file(s) currently open, instead of receiving the error "This action can't be completed because the folder or a file in it is open in another program," it would unlock these files (= automatically closing all processes that block the operation) and then rename the folder as originally desired?

**Comment by Maxhem2** [comment]
> Hi, do I understand correctly that what you'd expect from such a feature would be that when renaming a folder that contains file(s) currently open, instead of receiving the error "This action can't be completed because the folder or a file in it is open in another program," it would unlock these files (= automatically closing all processes that block the operation) and then rename the folder as originally desired?

Yes, spot on

**Comment by marianpekar** [comment]
Unfortunately, the requested feature would require the application to run in background all the time and that is too much outside the original design. Please feel free to use any part of the code in this repository as a basis or inspiration for a new application that would be designed in a way that it can have the requested feature. For doing so, this might be useful https://learn.microsoft.com/en-us/dotnet/api/system.io.filesystemwatcher?view=net-8.0
